# Generated by Django 6.0.3 on 2026-03-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emergencyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
