name: API CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # 1) SONARCLOUD ANALYSIS
  sonarcloud:
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        with:
          args: >
            -Dsonar.projectKey=RohitMane1208_Scalable-CC
            -Dsonar.organization=rohitmane1208
            -Dsonar.python.version=3.9
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=**/migrations/**,static/**,venv/**,db.sqlite3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}